import pptxgen from 'pptxgenjs';
import { PPTExportOptions } from '../types';
import { ExportSource, buildExportBlocks, imageToDataUri, resolveImage } from './exportUtils';

interface ThemeConfig {
  background: string;
  textColor: string;
  accentColor: string;
  subTextColor: string;
  fontFamily: string;
}

const THEMES: Record<string, ThemeConfig> = {
  light: {
    background: 'FFFFFF',
    textColor: '1A1A2E',
    accentColor: '4F46E5',
    subTextColor: '6B7280',
    fontFamily: 'Calibri',
  },
  dark: {
    background: '1A1A2E',
    textColor: 'FFFFFF',
    accentColor: '818CF8',
    subTextColor: 'A0AEC0',
    fontFamily: 'Calibri',
  },
  professional: {
    background: 'F8FAFC',
    textColor: '0F172A',
    accentColor: '0369A1',
    subTextColor: '475569',
    fontFamily: 'Calibri',
  },
};

export async function generatePowerPoint(
  source: ExportSource,
  options: PPTExportOptions
): Promise<Buffer> {
  try {
    const pptx = new pptxgen();
    const theme = THEMES[options.theme || 'professional'];
    const blocks = buildExportBlocks(source);

    pptx.defineLayout({ name: 'WIDESCREEN', width: 13.33, height: 7.5 });
    pptx.layout = 'WIDESCREEN';

    // ─── Title Slide ─────────────────────────────────────────────────────────
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: theme.background };

    titleSlide.addText(options.title || 'Presentation', {
      x: 0.5,
      y: 3,
      w: 12.33,
      h: 1.5,
      fontSize: 44,
      bold: true,
      color: theme.textColor,
      fontFace: theme.fontFamily,
      align: 'center',
    });

    titleSlide.addText('Generated by Ultimoversio', {
      x: 0.5,
      y: 4.8,
      w: 12.33,
      h: 0.5,
      fontSize: 16,
      color: theme.subTextColor,
      fontFace: theme.fontFamily,
      align: 'center',
    });

    // ─── Content Slides ───────────────────────────────────────────────────────
    if (blocks.length === 0) {
      // No sections - create a single slide with message
      const slide = pptx.addSlide();
      slide.background = { color: theme.background };
      slide.addText('No content available', {
        x: 0.5,
        y: 3,
        w: 12.33,
        h: 1,
        fontSize: 24,
        color: theme.subTextColor,
        fontFace: theme.fontFamily,
        align: 'center',
      });
      slide.addText('Please structure your document first', {
        x: 0.5,
        y: 4,
        w: 12.33,
        h: 0.5,
        fontSize: 14,
        color: theme.subTextColor,
        fontFace: theme.fontFamily,
        align: 'center',
      });
    } else {
      let slide = pptx.addSlide();
      slide.background = { color: theme.background };
      let currentTitle = options.title || 'Content';
      let y = 1.2;

      const addSlideWithTitle = (title: string) => {
        slide = pptx.addSlide();
        slide.background = { color: theme.background };
        currentTitle = title || 'Content';
        slide.addText(currentTitle, {
          x: 0.5,
          y: 0.4,
          w: 12.33,
          h: 0.6,
          fontSize: 26,
          bold: true,
          color: theme.accentColor,
          fontFace: theme.fontFamily,
        });
        y = 1.2;
      };

      addSlideWithTitle(currentTitle);

      for (const block of blocks) {
        if (block.type === 'heading') {
          addSlideWithTitle(block.text);
          continue;
        }

        if (block.type === 'paragraph' || block.type === 'blockquote') {
          const text = block.type === 'blockquote' ? `"${block.text}"` : block.text;
          const estimatedHeight = Math.max(0.5, Math.ceil(text.length / 90) * 0.34 + 0.12);
          if (y + estimatedHeight > 6.8) addSlideWithTitle(currentTitle);

          slide.addText(text, {
            x: 0.7,
            y,
            w: 11.9,
            h: estimatedHeight,
            fontSize: 17,
            color: theme.textColor,
            fontFace: theme.fontFamily,
            bold: block.type === 'blockquote',
            breakLine: true,
            valign: 'top',
          });
          y += estimatedHeight + 0.14;
          continue;
        }

        if (block.type === 'list') {
          for (let idx = 0; idx < block.items.length; idx++) {
            const item = `${block.ordered ? `${idx + 1}.` : '•'} ${block.items[idx]}`;
            const estimatedHeight = Math.max(0.35, Math.ceil(item.length / 95) * 0.3 + 0.08);
            if (y + estimatedHeight > 6.8) addSlideWithTitle(currentTitle);

            slide.addText(item, {
              x: 0.9,
              y,
              w: 11.4,
              h: estimatedHeight,
              fontSize: 16,
              color: theme.textColor,
              fontFace: theme.fontFamily,
              breakLine: true,
              valign: 'top',
            });
            y += estimatedHeight + 0.08;
          }
          y += 0.08;
          continue;
        }

        if (block.type === 'table') {
          for (const row of block.rows) {
            const rowText = row.join(' | ');
            const estimatedHeight = Math.max(0.3, Math.ceil(rowText.length / 96) * 0.3 + 0.08);
            if (y + estimatedHeight > 6.8) addSlideWithTitle(currentTitle);
            slide.addText(rowText, {
              x: 0.7,
              y,
              w: 11.9,
              h: estimatedHeight,
              fontSize: 14,
              color: theme.subTextColor,
              fontFace: theme.fontFamily,
            });
            y += estimatedHeight + 0.05;
          }
          y += 0.08;
          continue;
        }

        if (block.type === 'image') {
          const image = await resolveImage(block.src);
          if (!image) continue;
          const imageHeight = 2.2;
          if (y + imageHeight > 6.8) addSlideWithTitle(currentTitle);

          slide.addImage({
            data: imageToDataUri(image),
            x: 1.0,
            y,
            w: 11.3,
            h: imageHeight,
          });
          y += imageHeight + 0.16;
        }
      }
    }

    // ─── Thank You Slide ──────────────────────────────────────────────────────
    const endSlide = pptx.addSlide();
    endSlide.background = { color: theme.accentColor };

    endSlide.addText('Thank You', {
      x: 0,
      y: 3,
      w: 13.33,
      h: 1.5,
      fontSize: 48,
      bold: true,
      color: 'FFFFFF',
      fontFace: theme.fontFamily,
      align: 'center',
    });

    // Write to buffer
    console.log('[PPTX] Writing to buffer...');
    const buffer = await (pptx.write({ outputType: 'nodebuffer' }) as Promise<Buffer>);
    console.log('[PPTX] Buffer created, size:', buffer.length);
    return buffer;
  } catch (err) {
    console.error('[PPTX] Generation failed:', err);
    throw new Error('Failed to generate PowerPoint: ' + (err instanceof Error ? err.message : 'Unknown error'));
  }
}
